site_name: ACM/Cyber-Tech CTF 2.0
site_description: Official website for ACM/Cyber-Tech CTF 2.0, a cybersecurity collaboration between ACM and Cyber-Tech
site_url: https://psu-ctf.shoug-tech.com/
repo_url: https://github.com/Shoug-Alomran/psu-ctf2-web
repo_name: acm-ctf2-web
hooks:
  - build_hooks.py

theme:
  name: material
  custom_dir: docs/overrides
  favicon: image/index/ctf_logo.png
  palette:
    scheme: slate
    primary: cyan
    accent: blue
  font:
    text: Barlow
    code: Share Tech Mono
  features:
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.tooltips

nav:
  - Home: index.md
  - Agenda: agenda.md
  - Workshop: workshop.md
  - Presentation: presentation/index.md
  - Resources: resources.md
  - Challenges: challenges.md
  - Rules: rules.md
  - FAQ: faq.md
  - About: about.md
  - Products: products.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Shoug-Alomran/psu-ctf2-web
  event:
    date: "April 25, 2026"
    time: "10:00 AM - 1:00 PM"
    location: "Auditorium B105, 2nd Floor"

plugins:
  - search

copyright: "&copy; 2026 ACM/Cyber-Tech CTF 2.0 · ACM Student Chapter & Cyber-Tech Club · Prince Sultan University"
